project:
  type: website
  output-dir: docs

website:
  title: "Lindsay McNary - Tutorial Blog"
  description: "Learning how to API"
  
  navbar:
    background: primary
    left:
      - text: "Getting Started With APIs in Python"
        href: index.md
      
    right:
      - icon: github
        href: https://github.com/lmcnary



format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
